-- ============================================================
-- BANCO DO PROJETO DE VERSIONAMENTO
-- Execute este SQL no Supabase > SQL Editor.
-- ============================================================

create table if not exists public.versionamentos (
  id bigint generated by default as identity primary key,
  modelo_sistema text not null,
  versao text not null,
  data_digitada text not null,
  pdf_path text,
  criado_em timestamptz not null default now()
);

create table if not exists public.secoes (
  id bigint generated by default as identity primary key,
  versionamento_id bigint not null
    references public.versionamentos(id)
    on delete cascade,
  titulo text not null,
  ordem integer not null default 1,
  criado_em timestamptz not null default now()
);

create table if not exists public.itens (
  id bigint generated by default as identity primary key,
  secao_id bigint not null
    references public.secoes(id)
    on delete cascade,
  caminho_sistema text not null,
  descricao text not null,
  ordem integer not null default 1,
  criado_em timestamptz not null default now()
);

create index if not exists idx_secoes_versionamento
  on public.secoes(versionamento_id);

create index if not exists idx_itens_secao
  on public.itens(secao_id);

-- Segurança: o navegador NÃO acessará essas tabelas diretamente.
-- A Netlify Function usa a chave secreta do Supabase no servidor.
alter table public.versionamentos enable row level security;
alter table public.secoes enable row level security;
alter table public.itens enable row level security;

-- Não criamos policies para anon/authenticated.
-- A Function usa a secret key e, portanto, pode operar como backend confiável.

-- ============================================================
-- STORAGE
-- ============================================================

insert into storage.buckets (id, name, public)
values ('versionamentos-pdfs', 'versionamentos-pdfs', false)
on conflict (id) do update set public = false;

-- Sem policies para acesso público.
-- O PDF fica privado.
-- Futuramente, uma tela autenticada poderá gerar signed URLs.
